name: Docker image

on:
  push:
    branches:
      - 'main'
    # Only build Docker images if relevant files change.
    paths:
      - .github/workflows/docker.yml
      - src**
      - .dockerignore
      - Cargo*
      - Dockerfile

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: Docker
    concurrency:
      group: docker
      cancel-in-progress: true
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: klausi
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: klausi/mastodon-bluesky-sync:latest
          platforms: linux/amd64,linux/arm64
