on:
  push:
    # Only run Tests if Rust source files change.
    paths:
      - .github/workflows/testing.yml
      - src**
      - Cargo*
      - tests**
  pull_request:
    # Only run Tests if Rust source files change.
    paths:
      - .github/workflows/testing.yml
      - src**
      - Cargo*
      - tests**

name: Testing

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
      - run: |
          cargo check
          cargo test
          cargo fmt --all -- --check
          cargo clippy
